### ISSUE TITLE
Layer List - layer Description

### ISSUE THREAD

**Issue by TheFletcher** [CanterburyRegionalCouncil/CanterburyMaps_NativeMobile#10]
Description does not open rest end point for layer in web browser.
Suggest this function isn't required and Description option on layer options be removed.

**Comment by coomsie** [comment]
Does actually work, just not very well at all.... i dont believe it adds any value.

AGREE: Remove

Done through config file:

{
  "showLegend": true,
  "contextMenu": {
    "ZoomTo": true,
    "Transparency": true,
    "EnableOrDisablePopup": true,
    "MoveupOrMovedown": true,
    "OpenAttributeTable": true,
    **"DescriptionOrShowItemDetailsOrDownload": false**
  }
}

Done

https://github.com/CanterburyRegionalCouncil/CanterburyMaps_iOS/commit/650e9078178cea2aa9317b6df01c37f6b4179f0f
